spring.application.name=UserAuthAPI

#MySQL Database Configuration

# 1. K?t n?i MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#JWT Secret Key (In production, use a secure method to store this)
jwt.secret=9a67473a2620529166636306566676d0d0825310d6566676d0d0825310

